## Sample: 財務、金融の計算



### Numpy
Pythonでは大量のデータの処理や計算を実行するためのライブラリとして`Numpy`というものがあります。<BR>
    
このライブラリには金融の計算に使える機能もあるため、それを使ってライフプランニングチックなものをやっていきます。

### 具体例1: 住宅ローンの支払額

Numpyが提供している機能は色々ありますが、住宅ローンの支払額を簡単に求められる機能を提供しているので、それを使って月々のローンの支払額を求めていきます

In [33]:
import numpy as np

MONTHS_IN_YEAR = 12

# 支払総額(家の購入代金)
amount = 50000000
# 頭金
down_payment = 5000000
# 支払期間
duration = 25
# 金利
rate = 0.015

monthly_pay = int(np.pmt(
                    rate / MONTHS_IN_YEAR,
                    MONTHS_IN_YEAR * duration,
                    amount - down_payment)
                 )
total_amount = (monthly_pay * MONTHS_IN_YEAR * duration) - down_payment

print('月の支払額:', -monthly_pay)
print('支払総額:', -total_amount)

月の支払額: 179971
支払総額: 58991300


### 具体例２: 月々の収支の計算(住宅ローンを踏まえて)


年収が400万円と仮定して、ローン支払期間の余剰資金を計算してみたいと思います。
ここでも`Numpy`の利点を活かすことができます。

具体的にはPythonのListでは配列同士の数値演算は

In [56]:
income = 4000000

income_array = np.zeros(duration, dtype=np.int32)
loan_array = np.zeros(duration, dtype=np.int32)

income_array[:] = income
loan_array[:duration] = monthly_pay * MONTHS_IN_YEAR
loan_array[0] = loan_array[0] - down_payment

print(loan_array.sum())

-58991300


In [57]:
income_array

array([4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000,
       4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000,
       4000000, 4000000, 4000000, 4000000, 4000000, 4000000, 4000000,
       4000000, 4000000, 4000000, 4000000], dtype=int32)

In [58]:
loan_array

array([-7159652, -2159652, -2159652, -2159652, -2159652, -2159652,
       -2159652, -2159652, -2159652, -2159652, -2159652, -2159652,
       -2159652, -2159652, -2159652, -2159652, -2159652, -2159652,
       -2159652, -2159652, -2159652, -2159652, -2159652, -2159652,
       -2159652], dtype=int32)

#### Listの場合

List同士の演算は要素の連結になり、今回求めているような年ごとの収支計算はできない。

In [65]:
list_a = [4000000, 4000000]
list_b = [-7159652, -2159652]
list_a + list_b

[4000000, 4000000, -7159652, -2159652]

#### Numpyの場合

配列の要素数が同じであれば対応するインデックスごとの計算を自動で行ってくれるため、単純に足し算をするだけで年ごとの収支を計算することができる。

In [59]:
income_array + loan_array

array([-3159652,  1840348,  1840348,  1840348,  1840348,  1840348,
        1840348,  1840348,  1840348,  1840348,  1840348,  1840348,
        1840348,  1840348,  1840348,  1840348,  1840348,  1840348,
        1840348,  1840348,  1840348,  1840348,  1840348,  1840348,
        1840348], dtype=int32)

#### その他の機能
`Numpy`はその他にも計算に使える便利な機能を提供しており、以下は`cumusum()`メソッド(累積和の機能を提供)を使うことで年ごとの収支をもとに累積の残高を計算している。

In [60]:
np.cumsum(income_array + loan_array)

array([-3159652, -1319304,   521044,  2361392,  4201740,  6042088,
        7882436,  9722784, 11563132, 13403480, 15243828, 17084176,
       18924524, 20764872, 22605220, 24445568, 26285916, 28126264,
       29966612, 31806960, 33647308, 35487656, 37328004, 39168352,
       41008700])

ここで取り扱ったのは非常に単純化した収支の計算だったので計算結果にあまり意味はないかもしれませんが、<BR>
もっとたくさんの条件(例えば生活費とか子供の教育費とか)を追加することでシミュレーションとして有益な物を作ることもできると思います。
    
その場合にも`Numpy`の利点を活かせば、計算対象が増えたとしても単純な計算で収支の計算ができます。